name: Generate Snake Contribution

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate a snake animation
        uses: platane/snk@v3
        id: snake-svg
        with:
          github_user_name: alexalves011
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push new SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "chore: atualiza gráfico de cobra" || true
          git pull --rebase
          git push
